version: '3.8'

services:
  chatbot_web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://chatbot_user:1234@localhost:5432/chatbot_db
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=chatbot_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=chatbot_db
    ports:
      - "5432:5432"

      